application: thespoontravel
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
- url: /.*
  script: welcome.app

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest